"" Basic settings
set nocompatible                " be viMproved
set rtp+=$HOME/.vim/            " Does not seem to happen automatically in gvim
set dir=$HOME/.vim/swp          " Set swap dir
syntax enable                   " I like syntax highlighting
set encoding=utf-8              " Good default
filetype plugin indent on       " Load file type plugins + indentation
set number                      " Show line numbers
set hidden                      " Allow switching buffers without saving
set showcmd                     " Info about what we're doing

"" Colors
set background=light            " Light is good
"" colorscheme fruchtig

"" Whitespace
set nowrap                      " Don't wrap lines
set expandtab                   " Spaces instead of tabs
set tabstop=2                   " Insert 2 spaces on press of tab
set shiftwidth=2                " Indentation size
set backspace=indent,eol,start  " Backspace through everything in insert mode

"" Statusline
set laststatus=2                " Always show statusline
set statusline+=%F              " Add fully qualified filename to statusline
set statusline+=%=              " Add spacer
set statusline+=\ %l/%L         " Add current:total lines
set statusline+=\ ::\ %c        " Add current column

"" Searching
set hlsearch                    " Highlight matches
set incsearch                   " Keep searching as you type
set ignorecase                  " Searches are case insensitive
set smartcase                   " Unless they contain at least one capital letter

"" Cursor
set scrolloff=10                        " Show 10 lines above or below cursor
"" set colorcolumn=80,100                  " Know when the width gets too big
set cursorline                          " Show a line at the current cursor position
hi CursorLine cterm=NONE ctermbg=254    " But not too distracting
hi CursorColumn cterm=NONE ctermbg=254  " Same for when using this
let &t_SI = "\e[6 q"                    " Change cursor to caret in insert mode
let &t_EI = "\e[2 q"                    " Change cursor to block in normal mode

"" Tab completion in menus
set completeopt=menuone,menu,longest
set wildignore+=*\\tmp\\*,*.swp,*.swo,*.zip,.git,.cabal-sandbox
set wildmode=longest,list,full
set wildmenu

set t_Co=256

"" Whitespace / invisible characters
set listchars=eol:\ ,tab:\⇀\ ,trail:~,extends:>,precedes:<
set list                        " Make whitespace visible

"" Keymaps
nmap <Space> <Leader>
nmap <C-l> zz

" Files
nmap <Leader>frc :e ~/.vimrc<Enter>
nmap <Leader>fs :w<Enter>
nmap <Leader>fe :Explore<Enter>
nmap <Leader>qq :q<Enter>
let g:Lf_ShortcutF = '<leader>pf'

" Buffers
nmap <Leader>bd :bdelete<Enter>
let g:Lf_ShortcutB = '<leader>bb'

" Toggles
nmap <Leader>tc :set cursorcolumn!<Cr>            " Toggle the cursorcolumn
nmap <Leader>ts :if exists("g:syntax_on") <Bar> syntax off <Bar> else <Bar> syntax enable <Bar> endif <Cr>
nmap <Leader>th :nohl<Cr>

"" gvim
set guifont=DejaVu\ Sans\ Mono\ 7.5
set guioptions-=T            " Remove toolbar
set guioptions-=m            " Remove menu
set guioptions-=r            " Remove right scrollbar
set guioptions-=L            " Remove left scrollbar
set vb                       " visual bell
set t_vb=""                  " no beeping
set mousemodel=popup_setpos

"" Windows specific settings & overrides
if has("win32")
    set guifont=DejaVu_Sans_Mono:h9:cANSI
    set lines=80 columns=136 linespace=0
endif
